name: Daily Ping to DSA Reminder App

on:
  schedule:
    - cron: '55 3 * * *'
    - cron: '58 3 * * *'
    - cron: '00 4 * * *'
    - cron: '04 4 * * *'
    - cron: '07 4 * * *'
    - cron: '10 4 * * *'
    - cron: '13 4 * * *'
    - cron: '15 4 * * *'
    - cron: '18 4 * * *'
    - cron: '20 4 * * *'   # 09:55 AM IST
    - cron: '25 4 * * *'
    - cron: '28 4 * * *'
    
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to dsa-reminder-app with retry and logging
        run: |
          echo "Starting GET request at $(date -u) UTC"
          for i in {1..3}; do
            STATUS=$(curl -X GET -s -o response.txt -w "%{http_code}" https://dsa-reminder-app.onrender.com)
            echo "Attempt #$i - HTTP Status: $STATUS"
            if [[ "$STATUS" == 2* ]]; then
              echo "✅ Success"
              cat response.txt
              break
            elif [[ $i -eq 3 ]]; then
              echo "❌ Failed after 3 attempts"
              cat response.txt
              exit 1
            else
              echo "⚠️ Retrying in 10 seconds..."
              sleep 10
            fi
          done
